create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  type text not null check (type in ('bug', 'idea')),
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create index if not exists feedback_user_id_idx
  on public.feedback(user_id);

create table if not exists public.symptoms (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  cycle_id bigint references public.cycles(id) on delete cascade,
  symptom_date date not null,
  type text not null,
  intensity integer not null check (intensity between 1 and 5),
  created_at timestamptz not null default now()
);

create index if not exists symptoms_user_id_idx
  on public.symptoms(user_id);

create index if not exists symptoms_cycle_id_idx
  on public.symptoms(cycle_id);

create index if not exists notifications_user_id_idx
  on public.notifications(user_id);

notify pgrst, 'reload schema';
