alter table public.users
  add column if not exists platform text,
  add column if not exists onboarding_completed_at timestamptz,
  add column if not exists first_cycle_recorded_at timestamptz,
  add column if not exists last_active_at timestamptz,
  add column if not exists acquisition_source text,
  add column if not exists acquisition_campaign text,
  add column if not exists subscription_status text not null default 'free';

update public.users
set platform = case when telegram_id is not null then 'telegram' else 'kakao' end
where platform is null;

alter table public.users alter column platform set default 'kakao';
alter table public.users
  add constraint users_platform_check check (platform in ('telegram', 'kakao')) not valid;
alter table public.users validate constraint users_platform_check;
alter table public.users
  add constraint users_subscription_status_check check (subscription_status in ('free', 'plus', 'expired')) not valid;
alter table public.users validate constraint users_subscription_status_check;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  event_name text not null,
  platform text not null check (platform in ('telegram', 'kakao')),
  user_role text not null check (user_role in ('owner', 'partner')),
  source text,
  campaign text,
  created_at timestamptz not null default now()
);

alter table public.analytics_events enable row level security;

create index if not exists analytics_events_name_created_idx
  on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_events_user_created_idx
  on public.analytics_events(user_id, created_at desc);
create index if not exists users_growth_segments_idx
  on public.users(platform, mode, subscription_status);

grant all privileges on public.analytics_events to service_role;
notify pgrst, 'reload schema';
