create table if not exists public.users (
  id bigint generated by default as identity primary key,
  user_hash text not null unique,
  telegram_id bigint unique,
  language text not null default 'ru',
  timezone text not null default 'Asia/Seoul',
  cycle_length integer not null default 28 check (cycle_length between 15 and 60),
  period_length integer not null default 5 check (period_length between 1 and 14),
  mode text not null default 'female' check (mode in ('female', 'partner')),
  partner_code text unique,
  linked_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists users_telegram_id_idx
  on public.users(telegram_id);

create index if not exists users_partner_code_idx
  on public.users(partner_code);

create index if not exists users_linked_user_id_idx
  on public.users(linked_user_id);

create table if not exists public.cycles (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  period_start date not null,
  period_end date,
  cycle_length integer not null default 28 check (cycle_length between 15 and 60),
  period_length integer not null default 5 check (period_length between 1 and 14),
  created_at timestamptz not null default now(),
  constraint cycles_period_dates_check
    check (period_end is null or period_end >= period_start)
);

create index if not exists cycles_user_id_idx
  on public.cycles(user_id);

create index if not exists cycles_user_start_idx
  on public.cycles(user_id, period_start desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  type text not null,
  created_at timestamptz not null default now(),
  constraint notifications_user_type_key unique (user_id, type)
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  telegram_id bigint not null,
  amount_stars integer not null check (amount_stars > 0),
  payload text not null unique,
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'refunded')),
  telegram_payment_charge_id text unique,
  provider_payment_charge_id text,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists donations_user_id_idx
  on public.donations(user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

alter default privileges in schema public
  grant all privileges on tables to service_role;
alter default privileges in schema public
  grant all privileges on sequences to service_role;

notify pgrst, 'reload schema';
